// <auto-generated />
namespace Merchandising.DTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updateincomingpaymenttable20200307 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updateincomingpaymenttable20200307));
        
        string IMigrationMetadata.Id
        {
            get { return "202003061700389_Update incoming payment table 20200307"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
