// <auto-generated />
namespace Merchandising.DTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ReAddRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReAddRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "202001051557087_ReAdd Roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
